# ****************************************************************************
# Script: ai_enhanced_summarize_headlines_specific_stock.py
#
# Purpose:
# This script is part of a stock sentiment analysis pipeline designed to 
# analyze and summarize financial news headlines related to a specific stock 
# ticker symbol. It leverages AI to provide actionable insights by generating 
# a summary of relevant headlines and performing sentiment analysis (positive, 
# neutral, negative) on the news.
#
# Scope:
# - Input: Pre-processed JSON file containing headlines and sentiment scores 
#   for a specific stock ticker symbol (generated by a separate analysis script).
# - Process: 
#   1. Load and parse the JSON file for the selected stock.
#   2. Aggregate and count the sentiment of the headlines.
#   3. Use the Hugging Face `transformers` library to summarize all headlines 
#      into a concise and meaningful summary.
#   4. Save the sentiment breakdown and AI-generated summary to a text file.
# - Output: A text file containing:
#   1. Sentiment analysis breakdown (positive, neutral, negative).
#   2. AI-generated summary of the headlines.
#
# Logic:
# 1. Check for the existence of the pre-processed sentiment file for the given stock symbol.
# 2. Load the data and parse the headlines and sentiment scores.
# 3. Use the BART-Large CNN model from Hugging Face to create a text summary.
# 4. Save the sentiment count and AI-generated summary to a readable format.
#
# Dependencies:
# - Python 3.8+
# - Hugging Face Transformers library
# - Pre-processed JSON file with headline sentiment data
#
# Usage:
# 1. Ensure the sentiment analysis script is run first to generate the required JSON file.
# 2. Update the stock symbol (`processed_stock_symbol`) to match your target stock.
# 3. Run this script to generate the summary and sentiment breakdown.
#
# Example:
# Run the script with `python ai_enhanced_summarize_headlines_specific_stock.py`.
# The output will be saved in the `./data` folder.
#
# ****************************************************************************


import json
from transformers import pipeline
import os

def summarize_headlines(symbol):
    """
    Summarizes headlines and performs sentiment analysis for a specific stock ticker symbol.
    """

    # Path to the news file
    sentiment_file = f'./data/{symbol}_news_with_sentiment.json'

    # Check if the file exists
    if not os.path.exists(sentiment_file):
        print(f"Error: Sentiment file for {symbol} not found. Please run the analyze_sentiment script first.")
        return

    # Load the sentiment-processed news data
    with open(sentiment_file, 'r') as f:
        news_data = json.load(f)

    # Initialize counters and headline text collection
    sentiment_count = {'positive': 0, 'neutral': 0, 'negative': 0}
    relevant_headlines = []

    # Filter and summarize headlines for the selected symbol
    for article in news_data:
        sentiment = article.get('sentiment', None)  # Get sentiment or None if not available
        
        # Check for invalid sentiment and assign default 'neutral' if unknown
        if sentiment not in sentiment_count:
            sentiment = 'neutral'  # Default to 'neutral' if sentiment is missing or unknown
        sentiment_count[sentiment] += 1
        
        headline = article.get('headline', 'No headline available')
        relevant_headlines.append(headline)

    # Check if there are relevant headlines
    if not relevant_headlines:
        print(f"No relevant headlines found for {symbol}.")
        return

    # Create a summarization pipeline using Hugging Face transformers
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

    # Combine all relevant headlines into a single text block
    combined_text = " ".join(relevant_headlines)

    # Generate AI-based summary of the relevant headlines
    try:
        summary = summarizer(
            combined_text, max_length=100, min_length=30, do_sample=False
        )[0]['summary_text']
    except Exception as e:
        print(f"Error during summarization: {e}")
        summary = "Could not generate summary due to an error."

    # Save the sentiment count and summary to a text file
    summary_file = f'./data/{symbol}_headline_summary.txt'
    with open(summary_file, 'w') as f:
        f.write(f"Sentiment Analysis for {symbol}:\n")
        f.write(f"Positive: {sentiment_count['positive']}\n")
        f.write(f"Neutral: {sentiment_count['neutral']}\n")
        f.write(f"Negative: {sentiment_count['negative']}\n\n")
        f.write("AI-Generated Summary of Relevant Headlines:\n")
        f.write(summary)

    print(f"Headline summary saved to {summary_file}.")

if __name__ == "__main__":
    # Ensure this symbol matches the one used in the previous scripts
    processed_stock_symbol = "GS"  # Replace this with the variable symbol from analyze_sentiment
    summarize_headlines(processed_stock_symbol)
