# ****************************************************************************
# Script: summarize_headlines.py
#
# Purpose:
# This script summarizes the headlines and sentiment analysis for a selected 
# stock ticker symbol. It processes sentiment-annotated news data stored in 
# JSON format, generates a sentiment summary, and compiles a textual summary 
# of all headlines related to the selected stock. The results are saved to a 
# text file for easy review.
#
# Scope:
# - Input:
#   1. A stock ticker symbol selected by the user from a predefined list.
#   2. A pre-processed JSON file containing news headlines and their sentiment 
#      analysis (`<symbol>_news_with_sentiment.json`).
# - Process:
#   1. Read the news data for the specified stock symbol.
#   2. Aggregate sentiment counts (positive, neutral, negative).
#   3. Compile a summary of all headlines.
# - Output:
#   - A text file saved in the `./data` directory containing:
#     1. Sentiment analysis counts.
#     2. A concatenated summary of all headlines for the stock.
#
# Logic:
# 1. Check for the existence of the sentiment-processed news file. If missing, 
#    notify the user and exit.
# 2. Load the JSON data and count occurrences of each sentiment type.
# 3. Append each headline to a list and combine them into a single text block.
# 4. Save the sentiment analysis results and the headline summary to a text file.
# 5. Prompt the user to select a stock ticker from a list, ensuring valid input.
#
# Dependencies:
# - Python 3.8+
# - Libraries: `os`, `json`
# - Input JSON files must be generated by a prior script (e.g., analyze_sentiment.py).
#
# Usage:
# - Run the script and choose a stock symbol from the displayed list.
# - Ensure that the sentiment-annotated news JSON file for the selected stock 
#   exists in the `./data` directory.
#
# Example Workflow:
# 1. The user runs the script and selects a stock ticker (e.g., "AAPL").
# 2. The script processes the corresponding sentiment-annotated news file.
# 3. A sentiment count and a concatenated headline summary are generated and 
#    saved to a text file (e.g., `./data/AAPL_headline_summary.txt`).
#
# Notes:
# - If the required news file does not exist, the script will notify the user 
#   and exit without performing further operations.
# ****************************************************************************


import json
import os

def summarize_headlines(symbol):
    """
    Summarize the headlines and sentiments for a selected stock ticker.
    """
    # Define the path to the news file
    news_file = f'./data/{symbol}_news_with_sentiment.json'

    # Check if the news file exists
    if not os.path.exists(news_file):
        print(f"Error: News file for {symbol} not found.")
        return

    # Load the news data
    try:
        with open(news_file, 'r') as f:
            news_data = json.load(f)
    except json.JSONDecodeError:
        print(f"Error: Unable to decode JSON data from {news_file}.")
        return

    # Initialize counters and list for summaries
    sentiment_count = {'positive': 0, 'neutral': 0, 'negative': 0}
    summaries = []

    # Process and summarize headlines
    for article in news_data:
        sentiment = article.get('sentiment', 'neutral')  # Default to 'neutral' if sentiment is missing
        sentiment_count[sentiment] += 1
        headline = article.get('headline', '')
        summaries.append(headline)

    # Create a summary of all headlines
    summary_text = "\n".join(summaries)

    # Save the sentiment count and summary to a text file
    summary_file = f'./data/{symbol}_headline_summary.txt'
    os.makedirs('./data', exist_ok=True)
    with open(summary_file, 'w') as f:
        f.write(f"Sentiment Analysis for {symbol}:\n")
        f.write(f"Positive: {sentiment_count['positive']}\n")
        f.write(f"Neutral: {sentiment_count['neutral']}\n")
        f.write(f"Negative: {sentiment_count['negative']}\n\n")
        f.write("Summary of all news headlines:\n")
        f.write(summary_text)

    print(f"Headline summary saved to {summary_file}.")

if __name__ == "__main__":
    # Prompt the user for input
    ticker_symbols = ['AAPL', 'GOOGL', 'AMZN', 'MSFT', 'TSLA', 'META', 'NFLX', 
                      'NVDA', 'SPY', 'AMD', 'BA', 'DIS', 'GS', 'BRK.A', 'V']
    print("Please choose a stock symbol to summarize from the list below:")
    for idx, symbol in enumerate(ticker_symbols, start=1):
        print(f"{idx}. {symbol}")

    try:
        choice = int(input("\nEnter the number corresponding to your choice: "))
        if 1 <= choice <= len(ticker_symbols):
            selected_symbol = ticker_symbols[choice - 1]
            summarize_headlines(selected_symbol)
        else:
            print("Invalid choice. Please run the script again.")
    except ValueError:
        print("Invalid input. Please enter a valid number.")
